# Minimal local config; will be managed by Supabase CLI.
project_id = "local"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"

[storage]
file_size_limit = "50MiB"

